spring:
  datasource:
    url: jdbc:postgresql://192.168.110.222:5432/oa_crm_db_test
    username: highgo
    password: highgo@123
    driver-class-name: org.postgresql.Driver
#mybatis plus 设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fan.back.rest.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com:
      highgo:
        odid:
          rest: debug